-- =====================================================================
-- FOODY VRINDA: 24 GOURMET SATVIK DISH PRESETS SEED (V5.3.7)
-- High-Definition WebP Cutouts + Fallback CDN URLs + Nutrition Specs
-- =====================================================================

INSERT INTO public.foody_menus (
  id, shop_id, name, short_description, description, category, price, original_price, image, tag, calories, nutrition, is_available, is_veg
) VALUES
('preset-cheesy-veggie-pizza', 'shop-vrinda-main', 'Cheesy Veggie Pizza Slice', 'Cheesy artisan satvik slice', 'Oven-baked hand-tossed artisan pizza loaded with stretchy mozzarella cheese, fresh bell peppers, sweet corn, black olives, and Italian herbs.', 'Snacks', 160, 199, '/dishes/presets/cheesy-veggie-pizza-slice.webp', 'Chef Special', '280 kcal', '{"kcal": "280 kcal", "carbs": "36g", "protein": "11g", "fat": "12g"}'::jsonb, true, true),
('preset-chole-curry-naan', 'shop-vrinda-main', 'Amritsari Chole Naan Platter', 'Slow-cooked spiced chickpeas & naan', 'Slow-cooked Punjabi style spiced chickpeas simmered in aromatic gravy, served with fluffy butter garlic tandoori naan and pickled salad.', 'Meals', 190, 230, '/dishes/presets/chole-curry-naan-platter.webp', 'Devotee Favorite', '420 kcal', '{"kcal": "420 kcal", "carbs": "62g", "protein": "18g", "fat": "14g"}'::jsonb, true, true),
('preset-creamy-paneer-curry', 'shop-vrinda-main', 'Shahi Malai Paneer Bowl', 'Velvety cashew cream paneer', 'Velvety cashew and fresh cream gravy cooked with tender cubes of cottage cheese, fragrant green cardamom, and rich spices.', 'Meals', 220, 260, '/dishes/presets/creamy-paneer-curry-bowl.webp', 'Royal Classic', '360 kcal', '{"kcal": "360 kcal", "carbs": "18g", "protein": "16g", "fat": "24g"}'::jsonb, true, true),
('preset-crispy-samosas', 'shop-vrinda-main', 'Crispy Desi Samosas (2 pcs)', 'Flaky golden spiced potato samosas', 'Golden flaky crust stuffed with spiced potatoes, green peas, cashews, and whole roasted coriander seeds, served with sweet tamarind chutney.', 'Snacks', 60, 80, '/dishes/presets/crispy-samosas-basket.webp', 'All-Time Favorite', '220 kcal', '{"kcal": "220 kcal", "carbs": "28g", "protein": "5g", "fat": "11g"}'::jsonb, true, true),
('preset-crispy-spring-rolls', 'shop-vrinda-main', 'Crispy Veggie Spring Rolls', 'Crunchy golden rolls with sweet dip', 'Crunchy golden rolls filled with shredded seasonal vegetables, sprouts, and oriental seasoning, paired with sweet spicy garlic dip.', 'Snacks', 130, 160, '/dishes/presets/crispy-spring-rolls.webp', 'Crunchy Delight', '210 kcal', '{"kcal": "210 kcal", "carbs": "26g", "protein": "6g", "fat": "9g"}'::jsonb, true, true),
('preset-garlic-naan-chutneys', 'shop-vrinda-main', 'Butter Garlic Naan with Chutneys', 'Clay-oven baked butter garlic bread', 'Clay-oven baked leavened bread brushed with pure desi butter and freshly minced garlic, served with trio of heritage chutneys.', 'Meals', 90, 110, '/dishes/presets/garlic-naan-three-chutneys.webp', 'Tandoori Fresh', '240 kcal', '{"kcal": "240 kcal", "carbs": "38g", "protein": "7g", "fat": "8g"}'::jsonb, true, true),
('preset-glossy-kesar-jalebi', 'shop-vrinda-main', 'Desi Ghee Kesar Jalebi (100g)', 'Pure desi ghee saffron spirals', 'Crisp spiral delights fried in pure desi cow ghee and steeped in saffron-cardamom sugar nectar, garnished with Iranian pistachios.', 'Sweets & Prasad', 90, 120, '/dishes/presets/glossy-kesar-jalebi.webp', 'Pure Ghee', '290 kcal', '{"kcal": "290 kcal", "carbs": "56g", "protein": "3g", "fat": "8g"}'::jsonb, true, true),
('preset-glossy-hakka-noodles', 'shop-vrinda-main', 'Classic Veg Hakka Noodles', 'Wok-tossed noodles with greens', 'Wok-tossed noodles with shredded cabbage, bell peppers, carrots, and spring greens in a savory sesame-soy glaze.', 'Snacks', 140, 170, '/dishes/presets/glossy-stir-fried-noodles.webp', 'Wok Special', '310 kcal', '{"kcal": "310 kcal", "carbs": "48g", "protein": "8g", "fat": "10g"}'::jsonb, true, true),
('preset-schezwan-noodles', 'shop-vrinda-main', 'Spicy Schezwan Street Noodles', 'Fiery chili-garlic tossed noodles', 'Fiery chili-garlic tossed noodles packed with crunchy vegetables, baby corn, and aromatic scallions with bold Indo-Chinese flavors.', 'Snacks', 150, 180, '/dishes/presets/schezwan-veggie-noodles.webp', 'Spicy Hit', '330 kcal', '{"kcal": "330 kcal", "carbs": "50g", "protein": "8g", "fat": "12g"}'::jsonb, true, true),
('preset-golden-cheesy-puff', 'shop-vrinda-main', 'Golden Cheese & Corn Puff', 'Flaky multi-layered cheese pastry', 'Flaky multi-layered golden puff pastry filled with creamy melting cheese, sweet corn kernels, and Italian herbs.', 'Snacks', 70, 90, '/dishes/presets/golden-cheesy-triangle-puff.webp', 'Baked Fresh', '240 kcal', '{"kcal": "240 kcal", "carbs": "26g", "protein": "6g", "fat": "14g"}'::jsonb, true, true),
('preset-golden-chole-bhature', 'shop-vrinda-main', 'Royal Chole Bhature Feast (2 pcs)', 'Puffed golden bhature with chole', 'Puffed golden bhature served with rich dark spiced kabuli chana, tangy pickled chili, mint chutney, and spiced onion rings.', 'Meals', 180, 220, '/dishes/presets/golden-chole-bhature-feast.webp', 'Bestseller', '520 kcal', '{"kcal": "520 kcal", "carbs": "74g", "protein": "16g", "fat": "20g"}'::jsonb, true, true),
('preset-gooey-grilled-cheese', 'shop-vrinda-main', 'Gooey Grilled Cheese Sandwich', 'Melted cheddar & mozzarella toast', 'Toasted golden brown bread slices overflowing with melted cheddar and mozzarella cheese, ripe Roma tomato slices, and fresh basil.', 'Snacks', 130, 160, '/dishes/presets/gooey-grilled-cheese-tomato-basil.webp', 'Comfort Food', '310 kcal', '{"kcal": "310 kcal", "carbs": "32g", "protein": "12g", "fat": "16g"}'::jsonb, true, true),
('preset-bombay-club-sandwich', 'shop-vrinda-main', 'Bombay Veg Grilled Club Sandwich', 'Triple-decker layered club sandwich', 'Triple-decker grilled sandwich layered with spiced potato mash, sliced beetroot, cucumbers, tomatoes, green chutney, and melting cheese.', 'Snacks', 150, 180, '/dishes/presets/grilled-veg-cheese-sandwich-platter.webp', 'Popular Choice', '340 kcal', '{"kcal": "340 kcal", "carbs": "44g", "protein": "10g", "fat": "13g"}'::jsonb, true, true),
('preset-desi-grilled-sandwich', 'shop-vrinda-main', 'Classic Desi Grilled Sandwich', 'Crispy sandwich with mint spread', 'Crispy grilled sandwich with savory vegetable filling, aromatic mint-coriander spread, and golden toasted crust.', 'Snacks', 120, 150, '/dishes/presets/grilled-veggie-cheese-sandwich.webp', 'Quick Bite', '280 kcal', '{"kcal": "280 kcal", "carbs": "38g", "protein": "8g", "fat": "11g"}'::jsonb, true, true),
('preset-maharaja-fusion-burger', 'shop-vrinda-main', 'Maharaja Satvik Fusion Burger', 'Gourmet herb paneer brioche burger', 'Brioche bun stacked with crispy herb-paneer patty, grilled zucchini, farm fresh tomato, cheddar slice, and secret satvik signature sauce.', 'Snacks', 160, 199, '/dishes/presets/indulgent-fusion-burger.webp', 'Chef Special', '380 kcal', '{"kcal": "380 kcal", "carbs": "42g", "protein": "15g", "fat": "17g"}'::jsonb, true, true),
('preset-chole-tikki-chaat', 'shop-vrinda-main', 'Dilli Style Chole Tikki Chaat', 'Crisp potato patties with chole', 'Crisp shallow-fried golden potato cutlets drenched in hot spiced chole gravy, whipped sweetened yogurt, tamarind chutney, and fresh cilantro.', 'Snacks', 110, 140, '/dishes/presets/loaded-chole-aloo-tikki-chaat.webp', 'Street Favorite', '320 kcal', '{"kcal": "320 kcal", "carbs": "46g", "protein": "9g", "fat": "12g"}'::jsonb, true, true),
('preset-mathura-papdi-chaat', 'shop-vrinda-main', 'Special Mathura Papdi Chaat Bowl', 'Crisp papdis with sweet curd & sev', 'Crispy wheat flour crisps layered with boiled spiced potatoes, cooling sweetened curd, pomegranate seeds, nylon sev, and zesty chutneys.', 'Snacks', 100, 130, '/dishes/presets/loaded-papdi-chaat-bowl.webp', 'Must Try', '270 kcal', '{"kcal": "270 kcal", "carbs": "40g", "protein": "6g", "fat": "10g"}'::jsonb, true, true),
('preset-handi-paneer-curry', 'shop-vrinda-main', 'Desi Handi Paneer Korma', 'Smoky copper handi paneer', 'Tender paneer cubes cooked in traditional copper vessel with roasted whole spices, tomato puree, and infused with smoky desi ghee aroma.', 'Meals', 230, 270, '/dishes/presets/handi-paneer-curry.webp', 'Royal Feast', '390 kcal', '{"kcal": "390 kcal", "carbs": "20g", "protein": "18g", "fat": "27g"}'::jsonb, true, true),
('preset-pista-khoya-barfi', 'shop-vrinda-main', 'Shahi Pista Khoya Barfi (250g)', 'Pistachio saffron khoya sweet', 'Pure evaporated condensed milk confection enriched with roasted pistachio slivers, scented with pure Kashmiri saffron and green cardamom.', 'Sweets & Prasad', 180, 220, '/dishes/presets/pista-khoya-barfi.webp', 'Sacred Prasad', '380 kcal', '{"kcal": "380 kcal", "carbs": "52g", "protein": "10g", "fat": "15g"}'::jsonb, true, true),
('preset-seasoned-fries', 'shop-vrinda-main', 'Peri Peri Crispy French Fries', 'Zesty spiced golden french fries', 'Golden crispy potato fries tossed in zesty peri-peri seasoning and rock salt, served with tangy tomato dip.', 'Snacks', 90, 120, '/dishes/presets/seasoned-crispy-fries.webp', 'Crispy & Hot', '260 kcal', '{"kcal": "260 kcal", "carbs": "36g", "protein": "4g", "fat": "12g"}'::jsonb, true, true),
('preset-silver-kaju-katli', 'shop-vrinda-main', 'Royal Diamond Kaju Katli (250g)', 'Goan cashew fudge with silver vark', 'Mouth-melting diamond slices made from premium Goan cashews, refined sugar syrup, and adorned with traditional silver vark.', 'Sweets & Prasad', 240, 290, '/dishes/presets/silver-vark-kaju-katli.webp', 'Festive Special', '410 kcal', '{"kcal": "410 kcal", "carbs": "58g", "protein": "11g", "fat": "18g"}'::jsonb, true, true),
('preset-steamed-momos', 'shop-vrinda-main', 'Steamed Himalayan Veg Momos (6 pcs)', 'Steamed veggie & paneer dumplings', 'Delicately steamed dumplings packed with finely minced cabbage, carrots, bell peppers, ginger, and paneer, served with spicy red chutney.', 'Snacks', 110, 140, '/dishes/presets/steamed-veggie-momos.webp', 'Steamed Fresh', '190 kcal', '{"kcal": "190 kcal", "carbs": "32g", "protein": "7g", "fat": "4g"}'::jsonb, true, true),
('preset-farmhouse-pizza', 'shop-vrinda-main', 'Loaded Farmhouse Cheese Pizza (10")', 'Thin crust loaded farmhouse pizza', 'Freshly kneaded artisan crust topped with rich tomato sauce, extra mozzarella blend, mushrooms, bell peppers, onions, and sweet corn.', 'Snacks', 260, 320, '/dishes/presets/loaded-farmhouse-pizza.webp', 'Cheese Overload', '420 kcal', '{"kcal": "420 kcal", "carbs": "52g", "protein": "16g", "fat": "18g"}'::jsonb, true, true),
('preset-vibrant-dahi-vada', 'shop-vrinda-main', 'Vrindavan Special Dahi Vada Platter', 'Fluffy lentil dumplings in sweet yogurt', 'Soft fluffy lentil dumplings soaked in thick sweet creamy yogurt, topped with roasted cumin powder, red chili, black salt, and tamarind chutney.', 'Snacks', 120, 150, '/dishes/presets/vibrant-dahi-vada-chaat.webp', 'Temple Classic', '230 kcal', '{"kcal": "230 kcal", "carbs": "34g", "protein": "8g", "fat": "7g"}'::jsonb, true, true)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  image = EXCLUDED.image,
  tag = EXCLUDED.tag,
  calories = EXCLUDED.calories,
  nutrition = EXCLUDED.nutrition,
  is_available = EXCLUDED.is_available,
  is_veg = EXCLUDED.is_veg;
